# Generated by Django 4.0.4 on 2022-05-08 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('expiring_links', models.BooleanField()),
                ('original_image', models.BooleanField()),
                ('thumbnails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.thumbnail')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.user')),
            ],
        ),
    ]
