# Generated by Django 4.0.4 on 2022-05-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_tier_thumbnails_tier_thumbnails'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
    ]
