# Generated by Django 4.0.4 on 2022-05-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_user_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/API/images/'),
        ),
    ]
