# Generated by Django 4.0.4 on 2022-05-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_image_size_alter_tier_thumbnails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
