# Generated by Django 4.0.4 on 2022-05-13 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_rename_image_imagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='image',
            new_name='image_path',
        ),
    ]
