# Generated by Django 4.0.4 on 2022-05-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_rename_image_imagemodel_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image_path',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
