# Generated by Django 4.0.4 on 2022-05-13 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_remove_tier_users_usermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='tiers',
            new_name='tier',
        ),
    ]
