# Generated by Django 4.0.4 on 2022-05-13 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_rename_tiers_usermodel_tier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
