# Generated by Django 4.0.4 on 2022-05-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_usermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(default='test@email.com', max_length=255, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
