# Generated by Django 4.0.4 on 2022-05-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0021_usermodel_delete_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image_path',
            field=models.ImageField(blank=True, upload_to='static/images/'),
        ),
    ]
