# Generated by Django 4.0.4 on 2022-05-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0025_alter_imagemodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image_path',
            field=models.CharField(max_length=250),
        ),
    ]
