# Generated by Django 4.0.4 on 2022-05-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0027_alter_imagemodel_image_alter_imagemodel_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
