# Generated by Django 4.0.4 on 2022-05-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0028_alter_imagemodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='name',
        ),
    ]
