# Generated by Django 4.0.4 on 2022-05-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0030_alter_imagemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
